export const CHANGE_HERO_POSITION = "CHANGE_HERO_POSITION";
export const CHANGE_ENEMY_POSITIONS = "CHANGE_ENEMY_POSITIONS";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const CHANGE_GAME_STATUS = "CHANGE_GAME_STATUS";
export const RESET_POSITIONS = "RESET_POSITIONS";
export const RESET_GAME_STATUS = "RESET_GAME_STATUS";
